### ISSUE TITLE
Allow ordering from admin interface

### ISSUE THREAD

**Issue by sevrinsky** [sevrinsky/koopah#4]

**Comment by sarag18** [comment]
waiting with bated breath.....

**Comment by sarag18** [comment]
What's this?

On Sun, Dec 28, 2014 at 11:33 AM, sevrinsky notifications@github.com
wrote:

> Closed #4 https://github.com/sevrinsky/koopah/issues/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sevrinsky/koopah/issues/4#event-212263151.

## 

Sarah Gerskup
Licensed Tour guide - Israel
054-471-0636
02-534-6439

**Comment by sevrinsky** [comment]
Just tracking the work done -- ordering from admin interface was added a
while ago

You can safely ignore these emails.
- Richie
